services:
  loadbalance:
    image: nginx:1.27.0-alpine
    container_name: loadbalance
    ports:
      - "9090:80"

  node1:
    image: nginx:1.27.0-alpine
    container_name: node1
    volumes:
      - "/dist:/usr/share/nginx/html"

  node2:
    image: nginx:1.27.0-alpine
    container_name: node2
    volumes:
      - "/dist:/usr/share/nginx/html"

  node3:
    image: nginx:1.27.0-alpine
    container_name: node3
    volumes:
      - "/dist:/usr/share/nginx/html"
